name: Auth0 Configuration Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-dev:
    permissions:
      contents: read # Allows the workflow to read the repository contents
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      ENVIRONMENT_TYPE: dev
      TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
      TF_WORK_DIR: "terraform"
      TF_VAR_FILE: dev.tfvars
    secrets:
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

  deploy-test:
    needs: deploy-dev
    permissions:
      contents: read # Allows the workflow to read the repository contents
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      ENVIRONMENT_TYPE: test
      TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
      TF_WORK_DIR: "terraform"
      TF_VAR_FILE: test.tfvars
    secrets:
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

  deploy-prod:
    needs: deploy-test
    permissions:
      contents: read # Allows the workflow to read the repository contents
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      ENVIRONMENT_TYPE: prod
      TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
      TF_WORK_DIR: "terraform"
      TF_VAR_FILE: prod.tfvars
    secrets:
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
